# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b5b8ccbaf77b9a5cf2b4371817a3052bdac6c82f8b9908231172ec5f83763c1c0636e24aeffb9a3ca9ff069e7df078bcf5e4a3976cefe3214abe86227a3cd59

test:
  secret_key_base: f6f19c5e3b8dca4b3280a29ae8856783a66c59db36ffdff1f3494433d422967a55046eccde7a8f7a9dd030d03513ed1ef868ee5ca808a10b18956777efdf57fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
